"""chain-chat — ask Ethereum on-chain history in plain English.

A schema-aware LLM turns natural-language questions into SQL over a bundled
DuckDB/parquet snapshot of token transfers (USDC / UNI / WETH) and labeled
addresses. Runs fully offline with zero API keys (deterministic fallback),
or against any OpenAI-compatible endpoint when OPENAI_API_KEY is set.

No paid APIs, no mainnet funds — the bundled snapshot is synthetic
testnet-style data generated by scripts/fetch_parquet.py.
"""

__version__ = "0.1.0"