"""chain-chat — optional LIVE mode (BigQuery / public Ethereum data).

The default chain-chat experience is 100% offline: a bundled, synthetic
snapshot regenerated by scripts/fetch_parquet.py. No API keys, no paid APIs,
no mainnet funds.

This module sketches the optional live connector: fetch recent USDC / UNI /
WETH transfer events from a public dataset (e.g. BigQuery's
`bigquery-public-data.crypto_ethereum`). It is deliberately NOT wired into
the demo — it requires a user-provided GCP credential, which this project
does not ship.

Testnet-only data policy: live mode still reads public data only; it never
moves funds and never touches private keys.
"""

from __future__ import annotations

import os
from pathlib import Path


class LiveModeUnavailable(RuntimeError):
    """Raised when live mode is requested without credentials."""


def fetch_live_transfers(out_dir: str | Path) -> dict:
    """Fetch real transfer events into out_dir (BigQuery public dataset).

    Requires one of:
        GOOGLE_APPLICATION_CREDENTIALS  path to a GCP service-account JSON
        GCP_SERVICE_ACCOUNT_JSON        inline service-account JSON
        BIGQUERY_KEY                    same as GCP_SERVICE_ACCOUNT_JSON

    Without credentials this raises LiveModeUnavailable with instructions —
    chain-chat never blocks on missing keys: the offline snapshot is the demo.
    """
    creds = (
        os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
        or os.environ.get("GCP_SERVICE_ACCOUNT_JSON")
        or os.environ.get("BIGQUERY_KEY")
    )
    if not creds:
        raise LiveModeUnavailable(
            "live mode needs a user-provided GCP credential "
            "(GOOGLE_APPLICATION_CREDENTIALS / GCP_SERVICE_ACCOUNT_JSON / "
            "BIGQUERY_KEY). Run without --live for the offline snapshot."
        )
    # NOTE: the real connector would use `google-cloud-bigquery` to read
    # bigquery-public-data.crypto_ethereum.token_transfers and re-emit the
    # same transfers/labels/tokens parquet layout. Credentials are present;
    # wire it up here when you have a project id you trust.
    raise LiveModeUnavailable(
        "credential found, but the live BigQuery connector body is not "
        "bundled (needs google-cloud-bigquery + a project id). Offline mode "
        "is fully functional."
    )